/*******************************************************************************
// File Name :      SceneTransitionManager.cs
// Author :         Avery Macke, 
// Creation Date :  25 March 2022
// 
// Description :    Manages transitions and loading/unloading between scenes.
*******************************************************************************/
using UnityEngine;
using System.Collections;
using UnityEngine.SceneManagement;

public class SceneTransitionManager : MonoBehaviour
{
    [Tooltip("List of objects to retain during async scene transition")]
    public GameObject[] retainObjs = new GameObject[1];

    /// <summary>
    /// String name of artifact selected; used in level select
    /// </summary>
    private string artifact;

    /// <summary>
    /// String name of scene to load; used in level select
    /// </summary>
    private string sceneToLoad;

    /// <summary>
    /// String name of current scene
    /// </summary>
    private string currentScene;

    private SoundManager soundManager;

    /// <summary>
    /// 
    /// </summary>
    //private LevelSelectButtonsScript levelSelect;

    /// <summary>
    /// Called at start; gets name of current scene
    /// </summary>
    public void Start()
    {
        currentScene = SceneManager.GetActiveScene().name;
        soundManager = FindObjectOfType<SoundManager>();
    }

    /// <summary>
    /// Sets name of artifact level to be loaded; used in level select
    /// </summary>
    /// <param name="artifact">String name of artifact selected</param>
    public void SetArtifact(string artifact)
    {
        this.artifact = artifact;
    }

    /// <summary>
    /// Sets name of difficulty level to be loaded; used in level select
    /// </summary>
    /// <param name="difficulty">String name of difficulty selected</param>
    public void SetDifficulty(string difficulty)
    {
        sceneToLoad = artifact + difficulty;
    }

    ///// <summary>
    ///// 
    ///// </summary>
    ///// <param name="sceneToLoad"></param>
    //public void SetSceneToLoad(string difficulty)
    //{
    //    if (difficulty == "easy")
    //    {
    //        if (levelSelect.Rover)
    //            sceneToLoad = "RoverEasy";
    //        else
    //            sceneToLoad = "RocketEasy";
    //    }
    //    else if (difficulty == "medium")
    //    {
    //        if (levelSelect.Rover)
    //            sceneToLoad = "RoverMedium";
    //        else
    //            sceneToLoad = "RocketMedium";
    //    }
    //    else if (difficulty == "hard")
    //    {
    //        if (levelSelect.Rover)
    //            sceneToLoad = "RoverHard";
    //        else
    //            sceneToLoad = "RocketHard";
    //    }
    //}

    /// <summary>
    /// Loads scene selected in level select; takes scene generated by buttons
    /// </summary>
    public void LoadSceneLevelSelect()
    {
        SceneManager.LoadScene(sceneToLoad);
    }

    /// <summary>
    /// Loads new scene
    /// </summary>
    /// <param name="sceneName">String name of scene to load</param>
    public void LoadScene(string sceneName)
    {
        SceneManager.LoadScene(sceneName);

        if((sceneName == "LevelSelect" && currentScene != "Intro") 
            || sceneName == "MainMenu")
        {
            soundManager.Stop("Artifact Fixed");
            soundManager.Play("Stellar Station");
        }
    }

    /// <summary>
    /// Loads new scene asynchronously
    /// </summary>
    /// <param name="sceneName">String name of scene to load</param>
    public void LoadSceneAsync(string sceneName)
    {
        StartCoroutine("ChangeSceneAsync", sceneName);
    }

    /// <summary>
    /// Reloads the current scene
    /// </summary>
    public void LoadCurrentScene()
    {
        SceneManager.LoadScene(currentScene);
    }

    /// <summary>
    /// Loads gameplay scene; can move objects from one scene to another
    /// </summary>
    IEnumerator ChangeSceneAsync(string sceneName)
    {
        // Async loads gameplay scene
        Scene prevScene = (SceneManager.GetActiveScene());
        AsyncOperation asyncLoad = SceneManager.LoadSceneAsync(sceneName,
                                   LoadSceneMode.Additive);

        // Waits until loading is finished
        while (!asyncLoad.isDone)
        {
            yield return null;
        }

        // Transfers objects from current scene to new
        foreach (GameObject obj in retainObjs)
        {
            SceneManager.MoveGameObjectToScene(obj,
                         SceneManager.GetSceneByName(sceneName));
        }

        // Unloads customization scene
        SceneManager.UnloadSceneAsync(prevScene);
    }

    /// <summary>
    /// Quits game
    /// </summary>
    public void QuitGame()
    {
        Application.Quit();
    }
}
